os: linux
language: node_js
node_js: '10'
sudo: required
env: DISPLAY=':99.0'
dist: trusty
jobs:
  include:
    - stage: test google
      script: npm run test_google
before_install:
  - npm run installglobal
addons:
  chrome: stable
before_script:
  - sh -e /etc/init.d/xvfb start
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin