os: linux
language: node_js
node_js: '10'
sudo: false
dist: trusty
jobs:
  include:
    - stage: test google
      script: npm run test_google
before_install:
  - npm run installglobal
addons:
  apt:
    packages:
      - google-chrome-stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
  - google-chrome --product-version
  - webdriver-manager update --versions.chrome 77.0.3865.40