os: linux
sudo: required
language: node_js
node_js:
- 10
dist: trusty
jobs:
  include:
 - stage: test google
    script: npm run test_google
before_install:
  - npm run installglobal
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  global:
