os: linux
language: node_js
node_js: '10'
sudo: required
env: DISPLAY=':99.0'
dist: trusty
jobs:
  include:
    - stage: test google
      script: npm run test_google
before_install:
  - npm run installglobal
addons:
  chrome: stable
before_script:
  - sh -e /etc/init.d/xvfb start
  - webdriver-manager update --versions.chrome 76.0.3809.12